default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: hext_development

test:
  <<: *default
  database: hext_test

production:
  <<: *default
  database: hext_production
  username: hext
  password: <%= ENV['HEXT_DATABASE_PASSWORD'] %>
