default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter:  postgresql
  encoding: unicode
  pool:     5
  database: hext_production
  username: hext
  password: <%= ENV['HEXT_DATABASE_PASSWORD'] %>
