# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0585c148b20cc78326a904bdcd5eea7008916c1746b240f47d6e253ed5d9ab7999d8baa6db51e4a7a2917e391cd7d78a0108f29a71112b0de11ba2f9e4682ccc

test:
  secret_key_base: a7c951f876aab525c662bdac4c253cc76920641eec44d6ae40003c74a230ebead27d72edeeb66c3b1d78f4bb018679bacca87d0515c134e12f63ffda26ba5eb6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
